export interface SchoolMeta {
  name: string;
  shortName: string;
  location: string;
  type: string;
  enrollment: string;
  highlight: string;
  // Optional rich data for enhanced school pages
  strengths?: string[];         // Academic / research areas (shown as tags)
  careerStrengths?: string[];   // Career tracks the school is strong for
  signatureMajors?: string[];   // Notable or popular programs
  peerSlug?: string;            // Slug of a peer school for comparison prompt
  relatedSlugs?: string[];      // Related schools for navigation (same cluster, region, or type)
  freshmanNote?: string;        // What the first-year experience is distinctively like
}

export const SCHOOLS: Record<string, SchoolMeta> = {
  // ─── Ivies + MIT + Stanford ──────────────────────────────────────────────────
  columbia: {
    name: "Columbia University", shortName: "Columbia", location: "New York, NY",
    type: "Research University", enrollment: "~9,000 undergrads",
    highlight: "Full Columbia Bulletin integration with NIH grant data on faculty.",
    strengths: ["AI and data science", "economics", "biomedical research", "urban policy"],
    careerStrengths: ["tech and finance", "public policy", "healthcare"],
    signatureMajors: ["Computer Science", "Economics", "Political Science", "Neuroscience"],
    peerSlug: "yale",
    relatedSlugs: ["yale", "penn", "cornell"],
    freshmanNote: "The Core Curriculum structures your first two years — Contemporary Civilization and Literature Humanities are required for every student regardless of major.",
  },
  cornell: {
    name: "Cornell University", shortName: "Cornell", location: "Ithaca, NY",
    type: "Research University", enrollment: "~15,000 undergrads",
    highlight: "Cornell REST API — open/closed enrollment status across all seven colleges.",
    strengths: ["engineering", "hotel administration", "industrial labor relations", "agriculture and life sciences"],
    careerStrengths: ["engineering", "finance and consulting", "hospitality management"],
    signatureMajors: ["Computer Science", "Electrical Engineering", "Hotel Administration", "ILR"],
    peerSlug: "penn",
    relatedSlugs: ["penn", "columbia", "illinois"],
    freshmanNote: "All seven colleges share campus — first-years can explore across them before declaring and research labs actively recruit undergraduates.",
  },
  brown: {
    name: "Brown University", shortName: "Brown", location: "Providence, RI",
    type: "Research University", enrollment: "~7,000 undergrads",
    highlight: "Open Curriculum — every course searchable by concentration and WRIT designation.",
    strengths: ["neuroscience", "public health", "cognitive science", "environmental studies"],
    careerStrengths: ["healthcare and medicine", "research and academia", "public policy"],
    signatureMajors: ["Biology", "Computer Science", "Economics", "International Relations"],
    peerSlug: "wesleyan",
    relatedSlugs: ["yale", "dartmouth", "wesleyan"],
    freshmanNote: "Brown's Open Curriculum has no distributional requirements — you design your own academic path from day one.",
  },
  dartmouth: {
    name: "Dartmouth College", shortName: "Dartmouth", location: "Hanover, NH",
    type: "Liberal Arts College", enrollment: "~4,400 undergrads",
    highlight: "D-Plan and term-based enrollment data — including off-term availability.",
    strengths: ["environmental science", "quantitative social science", "engineering", "neuroscience"],
    careerStrengths: ["finance and consulting", "healthcare", "public service"],
    signatureMajors: ["Economics", "Government", "Engineering Sciences", "Biology"],
    peerSlug: "williams",
    relatedSlugs: ["brown", "williams", "middlebury"],
    freshmanNote: "The D-Plan means your first-year fall term is a compact, cohort-driven experience — and you'll return for multiple terms over four years.",
  },
  mit: {
    name: "MIT", shortName: "MIT", location: "Cambridge, MA",
    type: "Research University", enrollment: "~4,500 undergrads",
    highlight: "Live course catalog and schedule pages — including UROP research opportunities.",
    strengths: ["AI and machine learning", "aerospace engineering", "quantum computing", "bioengineering"],
    careerStrengths: ["deep tech and startups", "research and academia", "quantitative finance"],
    signatureMajors: ["Electrical Engineering", "Computer Science", "Physics", "Mathematics"],
    peerSlug: "stanford",
    relatedSlugs: ["stanford", "harveymudd", "cornell"],
    freshmanNote: "UROPs let first-years join faculty labs and get paid — nearly half of MIT undergrads participate before they leave.",
  },
  penn: {
    name: "University of Pennsylvania", shortName: "Penn", location: "Philadelphia, PA",
    type: "Research University", enrollment: "~10,000 undergrads",
    highlight: "Penn Catalog live data across Wharton, Engineering, College, and Nursing.",
    strengths: ["business and finance (Wharton)", "bioethics", "political science", "nursing"],
    careerStrengths: ["finance and consulting", "healthcare", "law"],
    signatureMajors: ["Finance (Wharton)", "Nursing", "Computer Science", "Political Science"],
    peerSlug: "columbia",
    relatedSlugs: ["columbia", "cornell", "notredame"],
    freshmanNote: "Penn's four undergraduate schools share a campus — first-years in Wharton can double-major in Engineering or the College from the start.",
  },
  stanford: {
    name: "Stanford University", shortName: "Stanford", location: "Stanford, CA",
    type: "Research University", enrollment: "~7,500 undergrads",
    highlight: "ExploreCourses XML API — real-time enrollment and quarter scheduling.",
    strengths: ["AI and machine learning", "bioengineering", "climate science and energy", "design thinking"],
    careerStrengths: ["deep tech and startups", "medicine", "climate and energy"],
    signatureMajors: ["Computer Science", "Human Biology", "Economics", "Product Design"],
    peerSlug: "mit",
    relatedSlugs: ["mit", "cornell", "brown"],
    freshmanNote: "STEM first-years often start research in autumn quarter — and the d.school's design thinking curriculum is open to all from day one.",
  },
  yale: {
    name: "Yale University", shortName: "Yale", location: "New Haven, CT",
    type: "Research University", enrollment: "~6,500 undergrads",
    highlight: "Full CourseLeaf integration — distributionals, skills, areas of inquiry.",
    strengths: ["humanities and arts", "global health", "environmental policy", "economics"],
    careerStrengths: ["law and policy", "medicine", "finance and consulting"],
    signatureMajors: ["Political Science", "Economics", "History", "Biology"],
    peerSlug: "columbia",
    relatedSlugs: ["columbia", "brown", "dartmouth"],
    freshmanNote: "The residential college system means first-year seminars, advising, and community are all within your assigned college.",
  },
  // ─── Research Universities ───────────────────────────────────────────────────
  baylor: {
    name: "Baylor University", shortName: "Baylor", location: "Waco, TX",
    type: "Research University", enrollment: "~17,000 undergrads",
    highlight: "R1 research university with health sciences and business live data.",
    strengths: ["health sciences", "business", "engineering", "law"],
    careerStrengths: ["healthcare and medicine", "business", "law and policy"],
    signatureMajors: ["Biology", "Business Administration", "Psychology", "Computer Science"],
    peerSlug: "notredame",
    relatedSlugs: ["notredame", "acu", "olemiss"],
  },
  gonzaga: {
    name: "Gonzaga University", shortName: "Gonzaga", location: "Spokane, WA",
    type: "Research University", enrollment: "~5,200 undergrads",
    highlight: "Jesuit liberal arts core with business and engineering live data.",
    strengths: ["business", "engineering", "philosophy", "nursing"],
    careerStrengths: ["business and consulting", "healthcare", "public service"],
    signatureMajors: ["Business Administration", "Mechanical Engineering", "Psychology", "Nursing"],
    peerSlug: "usfca",
    relatedSlugs: ["usfca", "usd", "notredame"],
  },
  gwu: {
    name: "George Washington University", shortName: "GWU", location: "Washington, DC",
    type: "Research University", enrollment: "~13,000 undergrads",
    highlight: "DC campus courses with policy, law, and public health specializations.",
    strengths: ["public policy", "international affairs", "public health", "political science"],
    careerStrengths: ["government and policy", "international affairs", "healthcare"],
    signatureMajors: ["Political Science", "International Affairs", "Public Health", "Finance"],
    peerSlug: "american",
    relatedSlugs: ["american", "georgetownlaw"],
  },
  illinois: {
    name: "University of Illinois Urbana-Champaign", shortName: "UIUC", location: "Urbana, IL",
    type: "Research University", enrollment: "~35,000 undergrads",
    highlight: "Grainger Engineering and iSchool courses via CISapp XML API — real-time.",
    strengths: ["computer science", "electrical engineering", "information science", "agricultural science"],
    careerStrengths: ["software engineering", "data science and AI", "agricultural technology"],
    signatureMajors: ["Computer Science", "Electrical Engineering", "Information Sciences", "Finance"],
    peerSlug: "notredame",
    relatedSlugs: ["cornell", "notredame"],
    freshmanNote: "Grainger's CS + X programs let students combine CS with almost any field — and first-years can register for declared-major courses from day one.",
  },
  jmu: {
    name: "James Madison University", shortName: "JMU", location: "Harrisonburg, VA",
    type: "Research University", enrollment: "~22,000 undergrads",
    highlight: "Health sciences, business, and education programs with live enrollment.",
    strengths: ["health sciences", "business", "education", "integrated science and technology"],
    careerStrengths: ["healthcare", "business", "education and teaching"],
    signatureMajors: ["Nursing", "Business Administration", "Health Sciences", "Psychology"],
    peerSlug: "radford",
    relatedSlugs: ["radford", "wm", "longwood"],
  },
  notredame: {
    name: "University of Notre Dame", shortName: "Notre Dame", location: "Notre Dame, IN",
    type: "Research University", enrollment: "~9,000 undergrads",
    highlight: "Mendoza Business, Law, and Engineering courses live via CourseLeaf.",
    strengths: ["business (Mendoza)", "law", "philosophy", "engineering"],
    careerStrengths: ["finance and consulting", "law", "engineering"],
    signatureMajors: ["Finance", "Political Science", "Computer Science", "Pre-Law"],
    peerSlug: "illinois",
    relatedSlugs: ["gonzaga", "usfca", "penn"],
  },
  olemiss: {
    name: "University of Mississippi", shortName: "Ole Miss", location: "Oxford, MS",
    type: "Research University", enrollment: "~23,000 undergrads",
    highlight: "SEC flagship with law, journalism, and pharmacy indexed.",
    strengths: ["law", "journalism and media studies", "pharmacy", "business management"],
    careerStrengths: ["law and policy", "journalism and media", "healthcare and pharmacy"],
    signatureMajors: ["Journalism", "Business Administration", "Pre-Law", "Pre-Pharmacy"],
    peerSlug: "baylor",
    relatedSlugs: ["baylor", "notredame"],
  },
  shu: {
    name: "Seton Hall University", shortName: "Seton Hall", location: "South Orange, NJ",
    type: "Research University", enrollment: "~6,000 undergrads",
    highlight: "Stillman School of Business and health science programs indexed.",
    strengths: ["business (Stillman School)", "nursing", "diplomacy and international relations", "communications"],
    careerStrengths: ["finance and business", "healthcare and nursing", "international affairs"],
    signatureMajors: ["Business Administration", "Nursing", "Diplomacy and International Studies", "Communications"],
    peerSlug: "american",
    relatedSlugs: ["american", "gwu", "niagara"],
  },
  // ─── Liberal Arts Colleges ───────────────────────────────────────────────────
  allegheny: {
    name: "Allegheny College", shortName: "Allegheny", location: "Meadville, PA",
    type: "Liberal Arts College", enrollment: "~1,600 undergrads",
    highlight: "Experiential learning and environmental science programs indexed.",
    strengths: ["environmental science", "communication arts", "neuroscience", "data science"],
    careerStrengths: ["environmental and sustainability careers", "communications and media", "research"],
    signatureMajors: ["Environmental Science", "Communication Arts", "Psychology", "Biology"],
    peerSlug: "fandm",
    relatedSlugs: ["fandm", "wooster", "muhlenberg"],
    freshmanNote: "Allegheny's Unusual Combination major lets students pair two fields from different divisions — like neuroscience and theatre — into a single integrated degree.",
  },
  american: {
    name: "American University", shortName: "American", location: "Washington, DC",
    type: "Liberal Arts College", enrollment: "~8,000 undergrads",
    highlight: "Policy, international studies, and public affairs courses with live enrollment.",
    strengths: ["international studies", "public policy", "communications", "law"],
    careerStrengths: ["government and policy", "international affairs", "media"],
    signatureMajors: ["International Studies", "Political Science", "Communications", "Pre-Law"],
    peerSlug: "gwu",
    relatedSlugs: ["gwu", "georgetownlaw"],
  },
  bates: {
    name: "Bates College", shortName: "Bates", location: "Lewiston, ME",
    type: "Liberal Arts College", enrollment: "~1,800 undergrads",
    highlight: "Live CourseLeaf data — including Short Term courses.",
    strengths: ["rhetoric and writing", "neuroscience", "biology", "economics"],
    careerStrengths: ["research and academia", "healthcare", "policy and public service"],
    signatureMajors: ["Biology", "Neuroscience", "Economics", "Political Science"],
    peerSlug: "middlebury",
    relatedSlugs: ["middlebury", "wesleyan", "williams"],
    freshmanNote: "Short Term, a four-week May intensive, is a Bates signature — first-years pursue focused independent research, fieldwork, or a single off-campus project.",
  },
  belmontuniv: {
    name: "Belmont University", shortName: "Belmont", location: "Nashville, TN",
    type: "Liberal Arts College", enrollment: "~8,500 undergrads",
    highlight: "Music business and entertainment programs with live enrollment.",
    strengths: ["music business", "entertainment industry", "healthcare", "business"],
    careerStrengths: ["music and entertainment", "healthcare", "business"],
    signatureMajors: ["Music Business", "Nursing", "Business Administration", "Recording Industry"],
  },
  berry: {
    name: "Berry College", shortName: "Berry", location: "Mount Berry, GA",
    type: "Liberal Arts College", enrollment: "~2,300 undergrads",
    highlight: "Animal science, health sciences, and business programs indexed.",
    strengths: ["animal science", "health sciences", "business", "education"],
    careerStrengths: ["veterinary and animal science", "healthcare", "business"],
    signatureMajors: ["Animal Science", "Business Administration", "Nursing", "Education"],
    peerSlug: "furman",
    relatedSlugs: ["furman", "davidson"],
  },
  brynmawr: {
    name: "Bryn Mawr College", shortName: "Bryn Mawr", location: "Bryn Mawr, PA",
    type: "Liberal Arts College", enrollment: "~1,400 undergrads",
    highlight: "Bi-Co cross-registration with Haverford included.",
    strengths: ["mathematics", "chemistry", "philosophy", "history"],
    careerStrengths: ["research and academia", "law", "healthcare"],
    signatureMajors: ["Mathematics", "Chemistry", "Psychology", "History"],
    peerSlug: "swarthmore",
    relatedSlugs: ["swarthmore", "fandm", "lafayette"],
    freshmanNote: "Bi-College registration with Haverford opens their full catalog to Bryn Mawr students from the start.",
  },
  calvin: {
    name: "Calvin University", shortName: "Calvin", location: "Grand Rapids, MI",
    type: "Liberal Arts College", enrollment: "~3,700 undergrads",
    highlight: "Engineering and science programs with faith integration indexed.",
    strengths: ["engineering", "chemistry and biology", "education", "business"],
    careerStrengths: ["engineering and technology", "education", "healthcare"],
    signatureMajors: ["Engineering", "Biology", "Business", "Education"],
    peerSlug: "hope",
    relatedSlugs: ["hope", "gonzaga"],
  },
  coloradocollege: {
    name: "Colorado College", shortName: "Colorado College", location: "Colorado Springs, CO",
    type: "Liberal Arts College", enrollment: "~2,200 undergrads",
    highlight: "Block Plan courses — one course at a time, fully indexed.",
    strengths: ["environmental studies", "neuroscience", "economics", "studio arts"],
    careerStrengths: ["environmental and outdoor careers", "healthcare", "arts and design"],
    signatureMajors: ["Environmental Science", "Biology", "Economics", "Studio Arts"],
    peerSlug: "wesleyan",
    relatedSlugs: ["cornellcollege", "wesleyan", "oberlin"],
    freshmanNote: "The Block Plan: one course at a time for 18 days. First-years experience total immersion in a single subject — then move on.",
  },
  cornellcollege: {
    name: "Cornell College", shortName: "Cornell College", location: "Mount Vernon, IA",
    type: "Liberal Arts College", enrollment: "~1,100 undergrads",
    highlight: "One Course At A Time — unique block plan with live enrollment.",
    strengths: ["interdisciplinary studies", "environmental science", "neuroscience", "studio arts"],
    careerStrengths: ["research and academia", "arts and design", "social services"],
    signatureMajors: ["Psychology", "Biology", "Economics", "Studio Art"],
    peerSlug: "coloradocollege",
    relatedSlugs: ["coloradocollege", "grinnell", "macalester"],
    freshmanNote: "Like Colorado College, Cornell's One Course At A Time plan means your entire focus goes to one course for three and a half weeks.",
  },
  davidson: {
    name: "Davidson College", shortName: "Davidson", location: "Davidson, NC",
    type: "Liberal Arts College", enrollment: "~2,000 undergrads",
    highlight: "Pre-professional advising and research programs fully indexed.",
    strengths: ["pre-medical sciences", "political science", "economics", "neuroscience"],
    careerStrengths: ["healthcare and medicine", "law and policy", "research"],
    signatureMajors: ["Biology", "Political Science", "Economics", "Psychology"],
    peerSlug: "furman",
    relatedSlugs: ["furman", "wm", "berry"],
    freshmanNote: "Davidson's Honor Code is nationally recognized — first-years learn to navigate academic integrity in an unusually trust-based environment.",
  },
  eastern: {
    name: "Eastern University", shortName: "Eastern", location: "St. Davids, PA",
    type: "Liberal Arts College", enrollment: "~3,800 undergrads",
    highlight: "Faith-integrated liberal arts with social work and nursing.",
  },
  endicott: {
    name: "Endicott College", shortName: "Endicott", location: "Beverly, MA",
    type: "Liberal Arts College", enrollment: "~4,500 undergrads",
    highlight: "Business, hospitality, and nursing programs with live enrollment.",
    strengths: ["nursing", "hospitality management", "business", "cybersecurity"],
    careerStrengths: ["healthcare and nursing", "hospitality and event management", "business"],
    signatureMajors: ["Nursing", "Hospitality and Tourism Management", "Business Administration", "Communication"],
    peerSlug: "merrimack",
    relatedSlugs: ["merrimack", "stonehill", "rivier"],
  },
  fandm: {
    name: "Franklin & Marshall College", shortName: "F&M", location: "Lancaster, PA",
    type: "Liberal Arts College", enrollment: "~2,400 undergrads",
    highlight: "Biological foundations and pre-health programs fully indexed.",
    strengths: ["neuroscience", "pre-health sciences", "government", "environmental science"],
    careerStrengths: ["healthcare and medicine", "law and policy", "research"],
    signatureMajors: ["Neuroscience", "Biology", "Government", "Psychology"],
    peerSlug: "muhlenberg",
    relatedSlugs: ["muhlenberg", "swarthmore", "brynmawr"],
  },
  furman: {
    name: "Furman University", shortName: "Furman", location: "Greenville, SC",
    type: "Liberal Arts College", enrollment: "~2,900 undergrads",
    highlight: "Engaged learning and sustainability programs with live data.",
    strengths: ["political science", "health sciences", "sustainability", "neuroscience"],
    careerStrengths: ["healthcare", "public service", "research"],
    signatureMajors: ["Biology", "Political Science", "Health Sciences", "Psychology"],
    peerSlug: "davidson",
    relatedSlugs: ["davidson", "berry", "wm"],
  },
  goucher: {
    name: "Goucher College", shortName: "Goucher", location: "Baltimore, MD",
    type: "Liberal Arts College", enrollment: "~1,400 undergrads",
    highlight: "International study requirement and arts programs indexed.",
    strengths: ["international studies", "arts", "communications", "psychology"],
    careerStrengths: ["arts and culture", "international affairs", "communications"],
    signatureMajors: ["Communications", "Psychology", "English", "International Studies"],
    peerSlug: "mcdaniel",
    relatedSlugs: ["mcdaniel", "american"],
  },
  grinnell: {
    name: "Grinnell College", shortName: "Grinnell", location: "Grinnell, IA",
    type: "Liberal Arts College", enrollment: "~1,700 undergrads",
    highlight: "Open curriculum and social justice programs with live enrollment.",
    strengths: ["social justice and sociology", "economics", "computer science", "biology"],
    careerStrengths: ["research and academia", "public policy", "social sector"],
    signatureMajors: ["Computer Science", "Biology", "Economics", "Political Science"],
    peerSlug: "oberlin",
    relatedSlugs: ["cornellcollege", "macalester", "oberlin"],
    freshmanNote: "Grinnell has no core requirements beyond a mandatory freshman seminar advising experience — everything else is yours to design.",
  },
  harveymudd: {
    name: "Harvey Mudd College", shortName: "Harvey Mudd", location: "Claremont, CA",
    type: "Engineering College", enrollment: "~900 undergrads",
    highlight: "Claremont consortium — the most STEM-dense college in the US, fully indexed.",
    strengths: ["applied mathematics", "engineering design", "computational science", "physics"],
    careerStrengths: ["engineering and R&D", "quantitative finance", "deep tech"],
    signatureMajors: ["Engineering", "Computer Science", "Mathematics", "Physics"],
    peerSlug: "rosehulman",
    relatedSlugs: ["pomona", "cmc", "rosehulman"],
    freshmanNote: "The Common Core is intense — every Harvey Mudd first-year takes the same demanding STEM sequence regardless of intended major.",
  },
  hope: {
    name: "Hope College", shortName: "Hope", location: "Holland, MI",
    type: "Liberal Arts College", enrollment: "~3,100 undergrads",
    highlight: "Sciences and pre-professional programs with live enrollment data.",
    strengths: ["chemistry and biochemistry", "engineering", "biology", "education"],
    careerStrengths: ["healthcare and medicine", "engineering", "education"],
    signatureMajors: ["Biology", "Chemistry", "Engineering", "Psychology"],
    peerSlug: "calvin",
    relatedSlugs: ["calvin", "macalester"],
    freshmanNote: "Hope is nationally recognized for undergraduate chemistry and biology research — students can join faculty labs as early as sophomore year with summer fellowships available.",
  },
  immaculata: {
    name: "Immaculata University", shortName: "Immaculata", location: "Immaculata, PA",
    type: "Liberal Arts College", enrollment: "~2,100 undergrads",
    highlight: "Health professions and education programs indexed live.",
    strengths: ["health professions", "education", "counseling psychology", "nursing"],
    careerStrengths: ["healthcare", "education and counseling", "social services"],
    signatureMajors: ["Nursing", "Education", "Psychology", "Dietetics"],
    peerSlug: "neumann",
    relatedSlugs: ["neumann", "misericordia", "eastern"],
  },
  lafayette: {
    name: "Lafayette College", shortName: "Lafayette", location: "Easton, PA",
    type: "Liberal Arts College", enrollment: "~2,700 undergrads",
    highlight: "Engineering at a liberal arts college — unique and fully indexed.",
    strengths: ["engineering", "economics", "neuroscience", "government and law"],
    careerStrengths: ["engineering", "finance", "research"],
    signatureMajors: ["Mechanical Engineering", "Economics", "Computer Science", "Government and Law"],
    peerSlug: "muhlenberg",
    relatedSlugs: ["muhlenberg", "fandm", "union"],
  },
  loras: {
    name: "Loras College", shortName: "Loras", location: "Dubuque, IA",
    type: "Liberal Arts College", enrollment: "~1,300 undergrads",
    highlight: "Catholic liberal arts with business and education programs indexed.",
    strengths: ["business", "education", "psychology", "philosophy"],
    careerStrengths: ["business", "education and teaching", "public service"],
    signatureMajors: ["Business Administration", "Education", "Psychology", "Finance"],
    peerSlug: "simpsonc",
    relatedSlugs: ["simpsonc", "cornellcollege", "wartburg"],
  },
  macalester: {
    name: "Macalester College", shortName: "Macalester", location: "St. Paul, MN",
    type: "Liberal Arts College", enrollment: "~2,200 undergrads",
    highlight: "International studies and civic engagement programs indexed.",
    strengths: ["international studies", "economics", "political science", "data science"],
    careerStrengths: ["international affairs", "public policy", "business and nonprofit"],
    signatureMajors: ["Economics", "Political Science", "International Studies", "Biology"],
    peerSlug: "grinnell",
    relatedSlugs: ["grinnell", "middlebury", "cornellcollege"],
    freshmanNote: "Macalester's Twin Cities location means first-years have immediate access to internships, civic engagement, and off-campus research.",
  },
  mcdaniel: {
    name: "McDaniel College", shortName: "McDaniel", location: "Westminster, MD",
    type: "Liberal Arts College", enrollment: "~1,600 undergrads",
    highlight: "Teacher education and social work programs fully indexed.",
    strengths: ["education", "social work", "business", "psychology"],
    careerStrengths: ["education and teaching", "social services", "business"],
    signatureMajors: ["Education", "Business Administration", "Social Work", "Psychology"],
    peerSlug: "goucher",
    relatedSlugs: ["goucher", "salisbury"],
  },
  merrimack: {
    name: "Merrimack College", shortName: "Merrimack", location: "North Andover, MA",
    type: "Liberal Arts College", enrollment: "~4,600 undergrads",
    highlight: "Nursing, business, and engineering programs with live enrollment.",
    strengths: ["nursing", "business", "engineering", "sports science"],
    careerStrengths: ["healthcare and nursing", "business", "engineering"],
    signatureMajors: ["Nursing", "Business Administration", "Civil Engineering", "Psychology"],
    peerSlug: "stonehill",
    relatedSlugs: ["stonehill", "endicott", "anselm"],
  },
  middlebury: {
    name: "Middlebury College", shortName: "Middlebury", location: "Middlebury, VT",
    type: "Liberal Arts College", enrollment: "~2,800 undergrads",
    highlight: "Language school and environmental studies courses with live enrollment.",
    strengths: ["environmental studies", "international and global studies", "language studies", "economics"],
    careerStrengths: ["international affairs", "climate and environment", "policy"],
    signatureMajors: ["Economics", "International Studies", "Environmental Studies", "Biology"],
    peerSlug: "wesleyan",
    relatedSlugs: ["bates", "williams", "wesleyan"],
    freshmanNote: "Winter Term is a three-week January intensive — research, independent study, or off-campus programs.",
  },
  morehouse: {
    name: "Morehouse College", shortName: "Morehouse", location: "Atlanta, GA",
    type: "Liberal Arts College", enrollment: "~2,200 undergrads",
    highlight: "STEM and social justice programs at a historic HBCU, fully indexed.",
    strengths: ["STEM and pre-medicine", "political science", "business administration", "social justice"],
    careerStrengths: ["medicine and healthcare", "public policy", "business"],
    signatureMajors: ["Biology", "Computer Science", "Business Administration", "Political Science"],
    peerSlug: "xaviernola",
    relatedSlugs: ["ncat", "morganstate", "xaviernola"],
    freshmanNote: "Crown Forum attendance in the first year builds community around Morehouse's mission and leadership tradition.",
  },
  muhlenberg: {
    name: "Muhlenberg College", shortName: "Muhlenberg", location: "Allentown, PA",
    type: "Liberal Arts College", enrollment: "~2,200 undergrads",
    highlight: "Theatre, film, and business programs with live course enrollment.",
    strengths: ["theatre arts", "film and media studies", "pre-health sciences", "business"],
    careerStrengths: ["arts and entertainment", "healthcare", "business"],
    signatureMajors: ["Theatre Arts", "Film Studies", "Business Administration", "Psychology"],
    peerSlug: "fandm",
    relatedSlugs: ["fandm", "lafayette", "elizabethtown"],
  },
  muskingum: {
    name: "Muskingum University", shortName: "Muskingum", location: "New Concord, OH",
    type: "Liberal Arts College", enrollment: "~1,900 undergrads",
    highlight: "Education and business programs with live enrollment data.",
    strengths: ["education", "business", "psychology", "biology"],
    careerStrengths: ["education and teaching", "business", "healthcare"],
    signatureMajors: ["Education", "Business Administration", "Psychology", "Biology"],
    peerSlug: "wooster",
    relatedSlugs: ["wooster", "ohiowesleyan", "heidelberg"],
  },
  ncwesleyan: {
    name: "North Carolina Wesleyan University", shortName: "NC Wesleyan", location: "Rocky Mount, NC",
    type: "Liberal Arts College", enrollment: "~1,800 undergrads",
    highlight: "Business, criminal justice, and education programs indexed.",
    strengths: ["business", "criminal justice", "education", "health sciences"],
    careerStrengths: ["business", "criminal justice", "education and teaching"],
    signatureMajors: ["Business Administration", "Criminal Justice", "Education", "Health Studies"],
    peerSlug: "winstonsalem",
    relatedSlugs: ["winstonsalem", "elizabethcitystate"],
  },
  niagara: {
    name: "Niagara University", shortName: "Niagara", location: "Niagara Falls, NY",
    type: "Liberal Arts College", enrollment: "~3,200 undergrads",
    highlight: "Education and criminology programs with live enrollment.",
    strengths: ["business", "education", "criminology", "nursing"],
    careerStrengths: ["business and consulting", "education", "healthcare and nursing"],
    signatureMajors: ["Business Administration", "Nursing", "Criminal Justice", "Education"],
    peerSlug: "shu",
    relatedSlugs: ["shu", "merrimack", "salve"],
  },
  oberlin: {
    name: "Oberlin College", shortName: "Oberlin", location: "Oberlin, OH",
    type: "Liberal Arts College", enrollment: "~2,900 undergrads",
    highlight: "Conservatory and College catalogs both indexed.",
    strengths: ["music and conservatory", "environmental studies", "neuroscience", "politics"],
    careerStrengths: ["arts and music", "research and academia", "policy and advocacy"],
    signatureMajors: ["Politics", "Environmental Studies", "Neuroscience", "Music Performance"],
    peerSlug: "grinnell",
    relatedSlugs: ["wooster", "grinnell", "ohiowesleyan"],
    freshmanNote: "Oberlin's conservatory and liberal arts college share courses — first-years can cross-register between them from the start.",
  },
  ohiowesleyan: {
    name: "Ohio Wesleyan University", shortName: "Ohio Wesleyan", location: "Delaware, OH",
    type: "Liberal Arts College", enrollment: "~1,600 undergrads",
    highlight: "Pre-professional programs and international studies indexed.",
    strengths: ["international studies", "pre-health sciences", "economics", "politics and government"],
    careerStrengths: ["international affairs", "healthcare and medicine", "business"],
    signatureMajors: ["Economics", "Politics and Government", "International Studies", "Biology"],
    peerSlug: "wooster",
    relatedSlugs: ["wooster", "oberlin", "muskingum"],
  },
  pointloma: {
    name: "Point Loma Nazarene University", shortName: "Point Loma", location: "San Diego, CA",
    type: "Liberal Arts College", enrollment: "~3,700 undergrads",
    highlight: "Sciences and pre-professional programs with live enrollment.",
    strengths: ["biology and nursing", "business", "engineering", "psychology"],
    careerStrengths: ["healthcare and nursing", "business", "engineering"],
    signatureMajors: ["Nursing", "Biology", "Business Administration", "Psychology"],
    peerSlug: "usd",
    relatedSlugs: ["usd", "gonzaga"],
  },
  providence: {
    name: "Providence College", shortName: "Providence", location: "Providence, RI",
    type: "Liberal Arts College", enrollment: "~4,200 undergrads",
    highlight: "Dominican liberal arts with business and health programs indexed.",
    strengths: ["business", "pre-health sciences", "political science", "liberal arts"],
    careerStrengths: ["business and consulting", "healthcare", "law and policy"],
    signatureMajors: ["Business Administration", "Biology", "Political Science", "Education"],
    peerSlug: "salve",
    relatedSlugs: ["salve", "gonzaga", "xavieru"],
  },
  rosehulman: {
    name: "Rose-Hulman Institute of Technology", shortName: "Rose-Hulman", location: "Terre Haute, IN",
    type: "Engineering College", enrollment: "~2,200 undergrads",
    highlight: "STEM-focused live catalog — every engineering discipline indexed.",
    strengths: ["mechanical engineering", "electrical engineering", "biomedical engineering", "computer science"],
    careerStrengths: ["engineering and manufacturing", "applied research", "tech and product development"],
    signatureMajors: ["Mechanical Engineering", "Electrical Engineering", "Computer Science", "Biomedical Engineering"],
    peerSlug: "harveymudd",
    relatedSlugs: ["harveymudd", "lafayette", "union"],
  },
  salve: {
    name: "Salve Regina University", shortName: "Salve Regina", location: "Newport, RI",
    type: "Liberal Arts College", enrollment: "~2,600 undergrads",
    highlight: "Live course data with nursing and cybersecurity programs.",
    strengths: ["nursing", "cybersecurity", "social work", "environmental studies"],
    careerStrengths: ["healthcare and nursing", "cybersecurity and tech", "social services"],
    signatureMajors: ["Nursing", "Cybersecurity", "Social Work", "Psychology"],
    peerSlug: "providence",
    relatedSlugs: ["providence", "merrimack", "endicott"],
  },
  shorter: {
    name: "Shorter University", shortName: "Shorter", location: "Rome, GA",
    type: "Liberal Arts College", enrollment: "~1,500 undergrads",
    highlight: "Business, nursing, and education programs with live enrollment.",
    strengths: ["business", "nursing", "education", "fine arts"],
    careerStrengths: ["business", "healthcare and nursing", "education"],
    signatureMajors: ["Business Administration", "Nursing", "Education", "Fine Arts"],
    peerSlug: "berry",
    relatedSlugs: ["berry", "tusculum"],
  },
  simpsonc: {
    name: "Simpson College", shortName: "Simpson", location: "Indianola, IA",
    type: "Liberal Arts College", enrollment: "~1,200 undergrads",
    highlight: "Pre-professional and arts programs with live enrollment data.",
    strengths: ["business", "arts and music", "education", "pre-health sciences"],
    careerStrengths: ["business", "arts and music", "education"],
    signatureMajors: ["Business Administration", "Music", "Education", "Biology"],
    peerSlug: "loras",
    relatedSlugs: ["loras", "cornellcollege", "wartburg"],
  },
  swarthmore: {
    name: "Swarthmore College", shortName: "Swarthmore", location: "Swarthmore, PA",
    type: "Liberal Arts College", enrollment: "~1,700 undergrads",
    highlight: "Full course catalog including Honors Program seminars.",
    strengths: ["physics", "economics", "political science", "cognitive science"],
    careerStrengths: ["research and academia", "policy and government", "healthcare"],
    signatureMajors: ["Computer Science", "Economics", "Biology", "Political Science"],
    peerSlug: "brynmawr",
    relatedSlugs: ["brynmawr", "fandm", "pomona"],
    freshmanNote: "Swarthmore's Honors Program lets high-achieving students take fewer, deeper seminars evaluated by external examiners in place of traditional courses.",
  },
  sweetbriar: {
    name: "Sweet Briar College", shortName: "Sweet Briar", location: "Sweet Briar, VA",
    type: "Liberal Arts College", enrollment: "~350 undergrads",
    highlight: "Engineering, arts, and equestrian programs at a women's college.",
    strengths: ["engineering", "studio arts", "environmental studies", "equestrian studies"],
    careerStrengths: ["engineering", "arts and design", "environmental careers"],
    signatureMajors: ["Engineering", "Studio Arts", "Environmental Studies", "Business"],
    peerSlug: "wesleyancollege",
    relatedSlugs: ["wesleyancollege", "scripps"],
  },
  transy: {
    name: "Transylvania University", shortName: "Transylvania", location: "Lexington, KY",
    type: "Liberal Arts College", enrollment: "~1,100 undergrads",
    highlight: "Pre-law, pre-health, and business programs with live enrollment.",
    strengths: ["pre-health sciences", "business", "law", "education"],
    careerStrengths: ["healthcare and medicine", "law", "business"],
    signatureMajors: ["Biology", "Business Administration", "Psychology", "Pre-Law"],
    peerSlug: "wooster",
    relatedSlugs: ["wooster", "ohiowesleyan", "muskingum"],
  },
  tusculum: {
    name: "Tusculum University", shortName: "Tusculum", location: "Greeneville, TN",
    type: "Liberal Arts College", enrollment: "~1,600 undergrads",
    highlight: "Civic arts curriculum with education and health programs indexed.",
    strengths: ["education", "business", "health sciences", "forensic science"],
    careerStrengths: ["education and teaching", "healthcare", "business"],
    signatureMajors: ["Education", "Business Administration", "Health Sciences", "Forensic Science"],
    peerSlug: "shorter",
    relatedSlugs: ["shorter", "berry"],
  },
  usfca: {
    name: "University of San Francisco", shortName: "USF", location: "San Francisco, CA",
    type: "Liberal Arts College", enrollment: "~6,500 undergrads",
    highlight: "Jesuit university with nursing, law, and business programs live.",
    strengths: ["nursing", "business", "law", "computer science"],
    careerStrengths: ["healthcare", "business and tech", "law and policy"],
    signatureMajors: ["Nursing", "Business Administration", "Computer Science", "International Studies"],
    peerSlug: "gonzaga",
    relatedSlugs: ["gonzaga", "usd"],
  },
  vassar: {
    name: "Vassar College", shortName: "Vassar", location: "Poughkeepsie, NY",
    type: "Liberal Arts College", enrollment: "~2,400 undergrads",
    highlight: "Live enrollment via ScheduleBrewer — real-time seat counts.",
    strengths: ["cognitive science", "political science", "drama", "environmental studies"],
    careerStrengths: ["arts and media", "policy", "research"],
    signatureMajors: ["Political Science", "English", "Psychology", "Biology"],
    peerSlug: "wesleyan",
    relatedSlugs: ["wesleyan", "middlebury", "bates"],
  },
  wartburg: {
    name: "Wartburg College", shortName: "Wartburg", location: "Waverly, IA",
    type: "Liberal Arts College", enrollment: "~1,600 undergrads",
    highlight: "Music, nursing, and business programs with live enrollment.",
    strengths: ["music", "nursing", "business", "education"],
    careerStrengths: ["arts and music", "healthcare and nursing", "business"],
    signatureMajors: ["Music", "Nursing", "Business Administration", "Education"],
    peerSlug: "simpsonc",
    relatedSlugs: ["simpsonc", "loras", "cornellcollege"],
  },
  wesleyan: {
    name: "Wesleyan University", shortName: "Wesleyan", location: "Middletown, CT",
    type: "Liberal Arts College", enrollment: "~3,000 undergrads",
    highlight: "Live enrollment data via WesMaps — know exactly which sections are open.",
    strengths: ["film studies", "neuroscience", "environmental studies", "music"],
    careerStrengths: ["media and entertainment", "research", "policy"],
    signatureMajors: ["Film Studies", "Neuroscience", "Psychology", "Biology"],
    peerSlug: "middlebury",
    relatedSlugs: ["middlebury", "bates", "vassar"],
    freshmanNote: "WesMaps lists every course with real-time enrollment — first-years can see exactly which sections have seats before they register.",
  },
  wesleyancollege: {
    name: "Wesleyan College", shortName: "Wesleyan College", location: "Macon, GA",
    type: "Liberal Arts College", enrollment: "~750 undergrads",
    highlight: "Historic women's college with business and communications indexed.",
    strengths: ["business", "communications", "education", "psychology"],
    careerStrengths: ["business", "communications and media", "education"],
    signatureMajors: ["Business Administration", "Communications", "Psychology", "Education"],
    peerSlug: "sweetbriar",
    relatedSlugs: ["sweetbriar", "brenau"],
  },
  westminsterpa: {
    name: "Westminster College", shortName: "Westminster", location: "New Wilmington, PA",
    type: "Liberal Arts College", enrollment: "~1,100 undergrads",
    highlight: "Sciences, education, and business programs with live data.",
    strengths: ["education", "business", "biology", "psychology"],
    careerStrengths: ["education and teaching", "business", "healthcare"],
    signatureMajors: ["Education", "Business Administration", "Biology", "Psychology"],
    peerSlug: "wooster",
    relatedSlugs: ["wooster", "westminsterpa"],
  },
  williams: {
    name: "Williams College", shortName: "Williams", location: "Williamstown, MA",
    type: "Liberal Arts College", enrollment: "~2,100 undergrads",
    highlight: "Tutorial program and Winter Study courses indexed live.",
    strengths: ["economics", "political science", "neuroscience", "environmental studies"],
    careerStrengths: ["finance", "research and academia", "public service"],
    signatureMajors: ["Economics", "Political Science", "History", "Biology"],
    peerSlug: "middlebury",
    relatedSlugs: ["middlebury", "wesleyan", "bates"],
    freshmanNote: "Winter Study (January) is a four-week term for something completely new — field work, travel, creative projects, or independent research.",
  },
  wooster: {
    name: "The College of Wooster", shortName: "Wooster", location: "Wooster, OH",
    type: "Liberal Arts College", enrollment: "~2,000 undergrads",
    highlight: "Independent Study program and STEM courses fully indexed.",
    strengths: ["biochemistry and chemistry", "political science", "music", "history"],
    careerStrengths: ["research and academia", "healthcare", "arts and music"],
    signatureMajors: ["Biology", "Psychology", "History", "Music"],
    peerSlug: "ohiowesleyan",
    relatedSlugs: ["ohiowesleyan", "oberlin", "grinnell"],
    freshmanNote: "Every Wooster student completes a senior Independent Study (IS) project — a full-year thesis advised one-on-one by a faculty mentor. First-year seminar builds the research skills IS demands.",
  },
  xavieru: {
    name: "Xavier University", shortName: "Xavier (OH)", location: "Cincinnati, OH",
    type: "Liberal Arts College", enrollment: "~7,400 undergrads",
    highlight: "Jesuit core curriculum with business and health programs indexed.",
    strengths: ["business", "health sciences", "philosophy", "psychology"],
    careerStrengths: ["business and consulting", "healthcare", "law"],
    signatureMajors: ["Business Administration", "Nursing", "Psychology", "Finance"],
    peerSlug: "gonzaga",
    relatedSlugs: ["gonzaga", "usfca", "notredame"],
  },
  xaviernola: {
    name: "Xavier University of Louisiana", shortName: "Xavier NOLA", location: "New Orleans, LA",
    type: "Liberal Arts College", enrollment: "~3,200 undergrads",
    highlight: "Largest HBCU pharmacy program — science and pre-health fully indexed.",
    strengths: ["pharmacy and pharmaceutical sciences", "pre-medicine", "chemistry", "biology"],
    careerStrengths: ["pharmacy", "medicine and healthcare", "research"],
    signatureMajors: ["Biology", "Chemistry", "Pre-Pharmacy", "Pre-Medicine"],
    peerSlug: "morehouse",
    relatedSlugs: ["morehouse", "ncat", "morganstate"],
    freshmanNote: "XULA's pharmacy pre-professional track is one of the most direct in the country — first-years begin foundational science coursework immediately.",
  },
  // ─── Public Universities ─────────────────────────────────────────────────────
  coppinstate: {
    name: "Coppin State University", shortName: "Coppin State", location: "Baltimore, MD",
    type: "Public University", enrollment: "~2,900 undergrads",
    highlight: "Nursing, education, and criminal justice programs at an HBCU.",
    strengths: ["nursing", "education", "criminal justice", "social work"],
    careerStrengths: ["healthcare and nursing", "education", "criminal justice"],
    signatureMajors: ["Nursing", "Education", "Criminal Justice", "Social Work"],
    peerSlug: "morganstate",
    relatedSlugs: ["morganstate", "winstonsalem", "ncat"],
  },
  csuci: {
    name: "CSU Channel Islands", shortName: "CSUCI", location: "Camarillo, CA",
    type: "Public University", enrollment: "~7,200 undergrads",
    highlight: "STEM and sustainability programs on a modern CSU campus.",
    strengths: ["environmental science", "liberal studies", "business", "computer science"],
    careerStrengths: ["environmental and sustainability careers", "education", "technology"],
    signatureMajors: ["Environmental Science and Resource Management", "Liberal Studies", "Business", "Computer Science"],
    peerSlug: "csueastbay",
    relatedSlugs: ["csueastbay", "csudh", "sonomastate"],
  },
  csueastbay: {
    name: "CSU East Bay", shortName: "CSUEB", location: "Hayward, CA",
    type: "Public University", enrollment: "~15,000 undergrads",
    highlight: "Business, nursing, and STEM programs serving the Bay Area.",
    strengths: ["business", "nursing", "computer science", "engineering"],
    careerStrengths: ["business", "healthcare and nursing", "technology"],
    signatureMajors: ["Business Administration", "Nursing", "Computer Science", "Criminal Justice"],
    peerSlug: "csun",
    relatedSlugs: ["csun", "csudh", "csuci"],
  },
  csuchico: {
    name: "Cal State Chico", shortName: "CSU Chico", location: "Chico, CA",
    type: "Public University", enrollment: "~17,000 undergrads",
    highlight: "STEM and sustainability programs with live enrollment data.",
    strengths: ["sustainable engineering", "nursing", "agriculture", "business"],
    careerStrengths: ["engineering and sustainability", "healthcare and nursing", "agriculture"],
    signatureMajors: ["Nursing", "Mechanical Engineering", "Business Administration", "Computer Science"],
    peerSlug: "sonomastate",
    relatedSlugs: ["sonomastate", "csun", "csueastbay"],
  },
  csudh: {
    name: "Cal State Dominguez Hills", shortName: "CSUDH", location: "Carson, CA",
    type: "Public University", enrollment: "~16,000 undergrads",
    highlight: "Diverse urban campus with nursing and business programs indexed.",
    strengths: ["nursing", "business", "health sciences", "STEM"],
    careerStrengths: ["healthcare and nursing", "business", "technology"],
    signatureMajors: ["Nursing", "Business Administration", "Computer Science", "Health Science"],
    peerSlug: "csun",
    relatedSlugs: ["csun", "csueastbay", "csuci"],
  },
  csun: {
    name: "Cal State Northridge", shortName: "CSUN", location: "Northridge, CA",
    type: "Public University", enrollment: "~38,000 undergrads",
    highlight: "One of the largest CSU campuses — business, arts, and engineering live.",
    strengths: ["arts, media, and communications", "engineering", "business", "nursing"],
    careerStrengths: ["media and entertainment", "engineering", "business"],
    signatureMajors: ["Business Administration", "Journalism", "Computer Science", "Cinema and Television Arts"],
    peerSlug: "csueastbay",
    relatedSlugs: ["csueastbay", "csudh", "csuchico"],
  },
  longwood: {
    name: "Longwood University", shortName: "Longwood", location: "Farmville, VA",
    type: "Public University", enrollment: "~5,400 undergrads",
    highlight: "Education, business, and natural sciences with live enrollment.",
    strengths: ["education", "business", "natural sciences", "liberal studies"],
    careerStrengths: ["education and teaching", "business", "healthcare"],
    signatureMajors: ["Education", "Business Administration", "Biology", "Psychology"],
    peerSlug: "radford",
    relatedSlugs: ["radford", "wm", "salisbury"],
  },
  morganstate: {
    name: "Morgan State University", shortName: "Morgan State", location: "Baltimore, MD",
    type: "Public University", enrollment: "~8,800 undergrads",
    highlight: "Engineering, business, and health programs at a major HBCU.",
    strengths: ["engineering", "business", "architecture", "public health"],
    careerStrengths: ["engineering", "business", "public health"],
    signatureMajors: ["Civil Engineering", "Business Administration", "Public Health", "Architecture"],
    peerSlug: "coppinstate",
    relatedSlugs: ["coppinstate", "ncat", "morehouse"],
  },
  radford: {
    name: "Radford University", shortName: "Radford", location: "Radford, VA",
    type: "Public University", enrollment: "~8,400 undergrads",
    highlight: "Health sciences, business, and arts programs with live enrollment.",
    strengths: ["health sciences", "communications", "art and design", "criminal justice"],
    careerStrengths: ["healthcare and nursing", "communications and media", "arts and design"],
    signatureMajors: ["Nursing", "Communications", "Psychology", "Criminal Justice"],
    peerSlug: "longwood",
    relatedSlugs: ["longwood", "wm", "jmu"],
  },
  salisbury: {
    name: "Salisbury University", shortName: "Salisbury", location: "Salisbury, MD",
    type: "Public University", enrollment: "~8,500 undergrads",
    highlight: "Business, nursing, and environmental programs indexed live.",
    strengths: ["business", "nursing", "environmental science", "education"],
    careerStrengths: ["healthcare and nursing", "business", "environmental careers"],
    signatureMajors: ["Business Administration", "Nursing", "Environmental Studies", "Education"],
    peerSlug: "wm",
    relatedSlugs: ["wm", "longwood", "radford"],
  },
  shenandoah: {
    name: "Shenandoah University", shortName: "Shenandoah", location: "Winchester, VA",
    type: "Public University", enrollment: "~4,400 undergrads",
    highlight: "Conservatory, pharmacy, and health programs with live data.",
    strengths: ["pharmacy", "health sciences", "music and conservatory", "business"],
    careerStrengths: ["pharmacy and healthcare", "arts and music", "business"],
    signatureMajors: ["Pharmacy", "Health Sciences", "Music Performance", "Business"],
    peerSlug: "radford",
    relatedSlugs: ["radford", "longwood"],
  },
  sonomastate: {
    name: "Sonoma State University", shortName: "Sonoma State", location: "Rohnert Park, CA",
    type: "Public University", enrollment: "~7,000 undergrads",
    highlight: "Business, environmental studies, and arts programs indexed.",
    strengths: ["environmental studies", "business", "arts and humanities", "education"],
    careerStrengths: ["environmental and sustainability careers", "business", "arts and design"],
    signatureMajors: ["Business Administration", "Environmental Studies", "Kinesiology", "Computer Science"],
    peerSlug: "csuchico",
    relatedSlugs: ["csuchico", "csuci", "csueastbay"],
  },
  uncpembroke: {
    name: "UNC Pembroke", shortName: "UNCP", location: "Pembroke, NC",
    type: "Public University", enrollment: "~8,600 undergrads",
    highlight: "Education, business, and nursing programs at a tribal-founded university.",
    strengths: ["education", "business", "nursing", "criminal justice"],
    careerStrengths: ["education and teaching", "healthcare and nursing", "business"],
    signatureMajors: ["Education", "Business Administration", "Nursing", "Criminal Justice"],
    peerSlug: "winstonsalem",
    relatedSlugs: ["winstonsalem", "elizabethcitystate"],
  },
  usd: {
    name: "University of San Diego", shortName: "USD", location: "San Diego, CA",
    type: "Research University", enrollment: "~5,700 undergrads",
    highlight: "Law, business, and engineering at a Catholic research university.",
    strengths: ["law", "business", "engineering", "political science"],
    careerStrengths: ["law and policy", "business", "engineering"],
    signatureMajors: ["Business Administration", "Pre-Law", "Political Science", "Engineering"],
    peerSlug: "usfca",
    relatedSlugs: ["gonzaga", "usfca"],
  },
  wou: {
    name: "Western Oregon University", shortName: "WOU", location: "Monmouth, OR",
    type: "Public University", enrollment: "~4,800 undergrads",
    highlight: "Education, criminal justice, and health programs with live data.",
    strengths: ["education", "criminal justice", "health sciences", "business"],
    careerStrengths: ["education and teaching", "criminal justice", "healthcare"],
    signatureMajors: ["Education", "Criminal Justice", "Health Sciences", "Business Administration"],
    peerSlug: "pacificu",
    relatedSlugs: ["pacificu", "stmarysca"],
  },
  // ─── Special / Niche ─────────────────────────────────────────────────────────
  georgetownlaw: {
    name: "Georgetown Law Center", shortName: "Georgetown Law", location: "Washington, DC",
    type: "Law School", enrollment: "~1,900 JD students",
    highlight: "Full JD and LLM course catalog with clinic and seminar enrollment.",
    strengths: ["constitutional law", "international law", "tax law", "environmental law"],
    careerStrengths: ["legal practice", "policy and government", "international affairs"],
    signatureMajors: ["JD", "LLM in International Law", "LLM in Tax", "LLM in Environmental Law"],
    relatedSlugs: ["gwu", "american"],
    freshmanNote: "1L courses are fully prescribed — Constitutional Law, Contracts, Torts, and Lawyering are required for every entering law student.",
  },
  // ─── Smaller regionals ───────────────────────────────────────────────────────
  anselm: {
    name: "Saint Anselm College", shortName: "Saint Anselm", location: "Manchester, NH",
    type: "Liberal Arts College", enrollment: "~2,000 undergrads",
    highlight: "Benedictine liberal arts with nursing and criminal justice programs.",
    strengths: ["criminal justice", "nursing", "philosophy", "political science"],
    careerStrengths: ["law and criminal justice", "healthcare and nursing", "public service"],
    signatureMajors: ["Criminal Justice", "Nursing", "Political Science", "Philosophy"],
    peerSlug: "nec",
    relatedSlugs: ["nec", "rivier", "merrimack"],
  },
  brenau: {
    name: "Brenau University", shortName: "Brenau", location: "Gainesville, GA",
    type: "Liberal Arts College", enrollment: "~2,000 undergrads",
    highlight: "Health sciences, arts, and education programs at a women's college.",
    strengths: ["nursing and health sciences", "arts", "education", "psychology"],
    careerStrengths: ["healthcare and nursing", "arts and design", "education"],
    signatureMajors: ["Nursing", "Occupational Therapy", "Fine Arts", "Education"],
    peerSlug: "wesleyancollege",
    relatedSlugs: ["wesleyancollege", "sweetbriar"],
  },
  chowan: {
    name: "Chowan University", shortName: "Chowan", location: "Murfreesboro, NC",
    type: "Liberal Arts College", enrollment: "~1,700 undergrads",
    highlight: "Communications, business, and sports management programs indexed.",
    strengths: ["communications", "business", "sports management", "education"],
    careerStrengths: ["communications and media", "business", "sports and athletics"],
    signatureMajors: ["Communications", "Business Administration", "Sport Management", "Education"],
    peerSlug: "ncwesleyan",
    relatedSlugs: ["ncwesleyan", "tusculum"],
  },
  cmc: {
    name: "Claremont McKenna College", shortName: "CMC", location: "Claremont, CA",
    type: "Liberal Arts College", enrollment: "~1,400 undergrads",
    highlight: "Government, economics, and pre-law in the Claremont consortium.",
    strengths: ["government and policy", "economics", "philosophy, politics & economics", "law"],
    careerStrengths: ["finance and consulting", "law and policy", "government"],
    signatureMajors: ["Government", "Economics", "Philosophy, Politics & Economics", "International Relations"],
    peerSlug: "pomona",
    relatedSlugs: ["pomona", "scripps", "pitzer"],
  },
  coastal: {
    name: "Coastal Carolina University", shortName: "Coastal Carolina", location: "Conway, SC",
    type: "Public University", enrollment: "~10,500 undergrads",
    highlight: "Marine science, hospitality, and business programs indexed live.",
    strengths: ["marine science", "hospitality management", "business", "health sciences"],
    careerStrengths: ["marine and environmental careers", "hospitality", "business"],
    signatureMajors: ["Marine Science", "Resort Tourism Management", "Business Administration", "Health Sciences"],
    relatedSlugs: ["uncpembroke", "salisbury"],
  },
  davenport: {
    name: "Davenport University", shortName: "Davenport", location: "Grand Rapids, MI",
    type: "Liberal Arts College", enrollment: "~6,500 undergrads",
    highlight: "Business, technology, and health programs with live enrollment.",
    strengths: ["business", "technology", "health informatics", "accounting"],
    careerStrengths: ["business and consulting", "technology", "healthcare administration"],
    signatureMajors: ["Business Administration", "Accounting", "Health Informatics", "Computer Science"],
    peerSlug: "calvin",
    relatedSlugs: ["calvin", "hope"],
  },
  ggc: {
    name: "Georgia Gwinnett College", shortName: "GGC", location: "Lawrenceville, GA",
    type: "Public University", enrollment: "~12,500 undergrads",
    highlight: "STEM, business, and health programs at a diverse public college.",
    strengths: ["STEM", "business", "health sciences", "information technology"],
    careerStrengths: ["technology", "business", "healthcare"],
    signatureMajors: ["Computer Science", "Business Administration", "Biology", "Information Technology"],
    peerSlug: "uncpembroke",
    relatedSlugs: ["uncpembroke", "fortvalleystate"],
  },
  heidelberg: {
    name: "Heidelberg University", shortName: "Heidelberg", location: "Tiffin, OH",
    type: "Liberal Arts College", enrollment: "~1,100 undergrads",
    highlight: "Business, education, and natural sciences with live enrollment.",
    strengths: ["business", "education", "biology", "psychology"],
    careerStrengths: ["business", "education and teaching", "healthcare"],
    signatureMajors: ["Business Administration", "Education", "Biology", "Psychology"],
    peerSlug: "muskingum",
    relatedSlugs: ["muskingum", "wooster", "ohiowesleyan"],
  },
  nec: {
    name: "New England College", shortName: "NEC", location: "Henniker, NH",
    type: "Liberal Arts College", enrollment: "~1,800 undergrads",
    highlight: "Education, social work, and environmental programs indexed.",
    strengths: ["education", "social work", "environmental science", "business"],
    careerStrengths: ["education and teaching", "social services", "environmental careers"],
    signatureMajors: ["Education", "Social Work", "Environmental Studies", "Business Administration"],
    peerSlug: "anselm",
    relatedSlugs: ["anselm", "rivier"],
  },
  pacificu: {
    name: "Pacific University", shortName: "Pacific", location: "Forest Grove, OR",
    type: "Liberal Arts College", enrollment: "~3,800 undergrads",
    highlight: "Health professions and optometry pre-professional programs indexed.",
    strengths: ["optometry and vision science", "health professions", "education", "business"],
    careerStrengths: ["optometry and vision care", "healthcare", "education"],
    signatureMajors: ["Pre-Optometry", "Nursing", "Education", "Business Administration"],
    peerSlug: "wou",
    relatedSlugs: ["wou", "stmarysca"],
  },
  pitzer: {
    name: "Pitzer College", shortName: "Pitzer", location: "Claremont, CA",
    type: "Liberal Arts College", enrollment: "~1,100 undergrads",
    highlight: "Social justice and environmental programs in the Claremont consortium.",
    strengths: ["social sciences", "environmental analysis", "media studies", "psychology"],
    careerStrengths: ["social sector and advocacy", "environmental careers", "media and communications"],
    signatureMajors: ["Sociology", "Environmental Analysis", "Psychology", "Media Studies"],
    peerSlug: "pomona",
    relatedSlugs: ["pomona", "scripps", "cmc"],
  },
  pomona: {
    name: "Pomona College", shortName: "Pomona", location: "Claremont, CA",
    type: "Liberal Arts College", enrollment: "~1,700 undergrads",
    highlight: "Top-ranked liberal arts college in the Claremont consortium.",
    strengths: ["economics", "computer science", "neuroscience", "politics and international relations"],
    careerStrengths: ["finance", "tech", "research and academia"],
    signatureMajors: ["Economics", "Computer Science", "Neuroscience", "Politics"],
    peerSlug: "swarthmore",
    relatedSlugs: ["cmc", "scripps", "harveymudd"],
    freshmanNote: "Pomona's Critical Inquiry seminars are the only required first-year courses — everything else is an open curriculum.",
  },
  rivier: {
    name: "Rivier University", shortName: "Rivier", location: "Nashua, NH",
    type: "Liberal Arts College", enrollment: "~2,700 undergrads",
    highlight: "Nursing, education, and business programs with live enrollment.",
    strengths: ["nursing", "education", "business", "psychology"],
    careerStrengths: ["healthcare and nursing", "education and teaching", "business"],
    signatureMajors: ["Nursing", "Education", "Business Administration", "Psychology"],
    peerSlug: "anselm",
    relatedSlugs: ["anselm", "nec", "merrimack"],
  },
  scripps: {
    name: "Scripps College", shortName: "Scripps", location: "Claremont, CA",
    type: "Liberal Arts College", enrollment: "~1,100 undergrads",
    highlight: "Humanities and interdisciplinary programs at a women's college.",
    strengths: ["humanities", "interdisciplinary studies", "arts", "environment"],
    careerStrengths: ["arts and publishing", "policy", "research and academia"],
    signatureMajors: ["Humanities", "Art History", "Environmental Analysis", "Politics"],
    peerSlug: "pomona",
    relatedSlugs: ["pomona", "cmc", "pitzer"],
    freshmanNote: "Scripps's Core Curriculum (Interdisciplinary Humanities) is a signature two-year program taken by every student.",
  },
  sienaheights: {
    name: "Siena Heights University", shortName: "Siena Heights", location: "Adrian, MI",
    type: "Liberal Arts College", enrollment: "~2,200 undergrads",
    highlight: "Business, education, and art programs with live enrollment.",
    strengths: ["business", "education", "art", "nursing"],
    careerStrengths: ["business", "education and teaching", "healthcare and nursing"],
    signatureMajors: ["Business Administration", "Education", "Art", "Nursing"],
    peerSlug: "calvin",
    relatedSlugs: ["calvin", "hope", "davenport"],
  },
  smumn: {
    name: "Saint Mary's University of Minnesota", shortName: "SMU MN", location: "Winona, MN",
    type: "Liberal Arts College", enrollment: "~5,600 undergrads",
    highlight: "Business, nursing, and education programs with live data.",
    strengths: ["business", "nursing", "education", "psychology"],
    careerStrengths: ["healthcare and nursing", "business", "education"],
    signatureMajors: ["Business Administration", "Nursing", "Education", "Psychology"],
    peerSlug: "macalester",
    relatedSlugs: ["macalester", "loras"],
  },
  stmarysca: {
    name: "Saint Mary's College of California", shortName: "Saint Mary's CA", location: "Moraga, CA",
    type: "Liberal Arts College", enrollment: "~4,000 undergrads",
    highlight: "Jan Term and LEAP program with business and education indexed.",
    strengths: ["business", "education", "communication", "kinesiology"],
    careerStrengths: ["business", "education and teaching", "communications"],
    signatureMajors: ["Business Administration", "Education", "Communication", "Kinesiology"],
    peerSlug: "gonzaga",
    relatedSlugs: ["gonzaga", "usfca", "pacificu"],
  },
  // ─── Added June 2026 ─────────────────────────────────────────────────────────
  reed: {
    name: "Reed College", shortName: "Reed", location: "Portland, OR",
    type: "Liberal Arts College", enrollment: "~1,400 undergrads",
    highlight: "One of the most academically rigorous colleges in the US — full catalog indexed.",
    strengths: ["physics", "chemistry", "literature and humanities", "mathematics"],
    careerStrengths: ["research and academia", "tech and software", "arts and publishing"],
    signatureMajors: ["Biology", "Physics", "Chemistry", "Literature"],
    peerSlug: "grinnell",
    relatedSlugs: ["grinnell", "oberlin", "wesleyan"],
    freshmanNote: "Hum 110, the year-long humanities conference, is Reed's foundational first-year course — every student takes it regardless of major.",
  },
  union: {
    name: "Union College", shortName: "Union", location: "Schenectady, NY",
    type: "Liberal Arts College", enrollment: "~2,200 undergrads",
    highlight: "Liberal arts and engineering programs — oldest non-sectarian college in NY.",
    strengths: ["engineering", "economics", "political science", "neuroscience"],
    careerStrengths: ["engineering", "finance", "research"],
    signatureMajors: ["Mechanical Engineering", "Economics", "Political Science", "Computer Science"],
    peerSlug: "lafayette",
    relatedSlugs: ["lafayette", "rosehulman", "harveymudd"],
  },
  stonehill: {
    name: "Stonehill College", shortName: "Stonehill", location: "Easton, MA",
    type: "Liberal Arts College", enrollment: "~2,700 undergrads",
    highlight: "Business, health sciences, and liberal arts programs indexed.",
    strengths: ["business", "health sciences", "education", "psychology"],
    careerStrengths: ["business", "healthcare", "education"],
    signatureMajors: ["Business Administration", "Nursing", "Psychology", "Education"],
    peerSlug: "merrimack",
    relatedSlugs: ["merrimack", "endicott", "anselm"],
  },
  nwmissouri: {
    name: "Northwest Missouri State University", shortName: "NWMSU", location: "Maryville, MO",
    type: "Public University", enrollment: "~6,200 undergrads",
    highlight: "Agriculture, education, and business programs with full catalog.",
    strengths: ["agriculture", "education", "business", "computer science"],
    careerStrengths: ["agriculture and food science", "education and teaching", "business"],
    signatureMajors: ["Agriculture", "Education", "Business Administration", "Computer Science"],
    peerSlug: "sfasu",
    relatedSlugs: ["sfasu", "midwesternstate"],
  },
  wm: {
    name: "College of William & Mary", shortName: "William & Mary", location: "Williamsburg, VA",
    type: "Research University", enrollment: "~6,300 undergrads",
    highlight: "Second-oldest college in the US — law, business, and STEM indexed.",
    strengths: ["law and legal studies", "marine science", "international affairs", "economics"],
    careerStrengths: ["law and policy", "environmental and marine careers", "finance"],
    signatureMajors: ["Economics", "Government", "Psychology", "Biology"],
    peerSlug: "davidson",
    relatedSlugs: ["davidson", "radford", "salisbury"],
  },
  tougaloo: {
    name: "Tougaloo College", shortName: "Tougaloo", location: "Jackson, MS",
    type: "Liberal Arts College", enrollment: "~900 undergrads",
    highlight: "Historic HBCU in Mississippi — full academic catalog indexed.",
    strengths: ["biology", "social sciences", "humanities", "education"],
    careerStrengths: ["medicine and healthcare", "education", "research and academia"],
    signatureMajors: ["Biology", "Psychology", "History", "Education"],
    peerSlug: "morehouse",
    relatedSlugs: ["morehouse", "xaviernola", "fortvalleystate"],
  },
  carroll: {
    name: "Carroll University", shortName: "Carroll", location: "Waukesha, WI",
    type: "Liberal Arts College", enrollment: "~3,200 undergrads",
    highlight: "Health sciences, engineering, and business programs indexed.",
    strengths: ["health sciences", "engineering", "business", "education"],
    careerStrengths: ["healthcare and physical therapy", "engineering", "business"],
    signatureMajors: ["Physical Therapy", "Engineering", "Business Administration", "Psychology"],
    peerSlug: "hope",
    relatedSlugs: ["hope", "calvin", "wartburg"],
  },
  malone: {
    name: "Malone University", shortName: "Malone", location: "Canton, OH",
    type: "Liberal Arts College", enrollment: "~1,400 undergrads",
    highlight: "Christian liberal arts with nursing and social work programs.",
    strengths: ["nursing", "social work", "business", "education"],
    careerStrengths: ["healthcare and nursing", "social services", "business"],
    signatureMajors: ["Nursing", "Social Work", "Business Administration", "Education"],
    peerSlug: "wooster",
    relatedSlugs: ["wooster", "heidelberg", "muskingum"],
  },
  baldwinwallace: {
    name: "Baldwin Wallace University", shortName: "BW", location: "Berea, OH",
    type: "Liberal Arts College", enrollment: "~3,500 undergrads",
    highlight: "Conservatory and liberal arts — business and health sciences indexed.",
    strengths: ["music and conservatory", "business", "health sciences", "education"],
    careerStrengths: ["arts and music", "business", "healthcare"],
    signatureMajors: ["Music Performance", "Business Administration", "Health Sciences", "Education"],
    peerSlug: "wooster",
    relatedSlugs: ["wooster", "oberlin", "ohiowesleyan"],
  },
  mountstmarys: {
    name: "Mount St. Mary's University", shortName: "Mount St. Mary's", location: "Emmitsburg, MD",
    type: "Liberal Arts College", enrollment: "~2,000 undergrads",
    highlight: "Catholic liberal arts with business, education, and nursing.",
    strengths: ["business", "education", "nursing", "theology"],
    careerStrengths: ["business", "education and teaching", "healthcare and nursing"],
    signatureMajors: ["Business Administration", "Education", "Nursing", "Psychology"],
    peerSlug: "mcdaniel",
    relatedSlugs: ["mcdaniel", "goucher", "salisbury"],
  },
  neumann: {
    name: "Neumann University", shortName: "Neumann", location: "Aston, PA",
    type: "Liberal Arts College", enrollment: "~2,800 undergrads",
    highlight: "Franciscan university with nursing, education, and business programs.",
    strengths: ["nursing", "education", "business", "criminal justice"],
    careerStrengths: ["healthcare and nursing", "education", "business"],
    signatureMajors: ["Nursing", "Education", "Business Administration", "Criminal Justice"],
    peerSlug: "misericordia",
    relatedSlugs: ["misericordia", "immaculata", "eastern"],
  },
  johnbrown: {
    name: "John Brown University", shortName: "JBU", location: "Siloam Springs, AR",
    type: "Liberal Arts College", enrollment: "~2,100 undergrads",
    highlight: "Christian liberal arts with engineering and business programs.",
    strengths: ["engineering", "business", "nursing", "education"],
    careerStrengths: ["engineering", "healthcare and nursing", "business"],
    signatureMajors: ["Engineering", "Business Administration", "Nursing", "Education"],
    peerSlug: "harding",
    relatedSlugs: ["acu", "harding", "texaslutheran"],
  },
  elizabethtown: {
    name: "Elizabethtown College", shortName: "Etown", location: "Elizabethtown, PA",
    type: "Liberal Arts College", enrollment: "~1,800 undergrads",
    highlight: "Peace and justice emphasis with strong health sciences programs.",
    strengths: ["health sciences", "business", "education", "social work"],
    careerStrengths: ["healthcare", "business", "social services"],
    signatureMajors: ["Occupational Therapy", "Business Administration", "Education", "Social Work"],
    peerSlug: "muhlenberg",
    relatedSlugs: ["muhlenberg", "fandm", "moravian"],
  },
  champlain: {
    name: "Champlain College", shortName: "Champlain", location: "Burlington, VT",
    type: "Liberal Arts College", enrollment: "~3,000 undergrads",
    highlight: "Career-focused education with game design, cybersecurity, and business.",
    strengths: ["game design", "cybersecurity", "business", "filmmaking"],
    careerStrengths: ["game and software development", "cybersecurity", "business and entrepreneurship"],
    signatureMajors: ["Game Design", "Cybersecurity", "Business of Creative Arts", "Computer Science"],
    relatedSlugs: ["salve", "endicott"],
  },
  moravian: {
    name: "Moravian University", shortName: "Moravian", location: "Bethlehem, PA",
    type: "Liberal Arts College", enrollment: "~2,000 undergrads",
    highlight: "One of America's oldest universities — nursing and business indexed.",
    strengths: ["nursing", "business", "education", "music"],
    careerStrengths: ["healthcare and nursing", "business", "education"],
    signatureMajors: ["Nursing", "Business Administration", "Education", "Music"],
    peerSlug: "muhlenberg",
    relatedSlugs: ["muhlenberg", "elizabethtown", "wilkes"],
  },
  misericordia: {
    name: "Misericordia University", shortName: "Misericordia", location: "Dallas, PA",
    type: "Liberal Arts College", enrollment: "~2,800 undergrads",
    highlight: "Catholic university with strong health professions programs.",
    strengths: ["health professions", "nursing", "occupational therapy", "business"],
    careerStrengths: ["healthcare and allied health", "nursing", "business"],
    signatureMajors: ["Nursing", "Occupational Therapy", "Physical Therapy", "Business Administration"],
    peerSlug: "neumann",
    relatedSlugs: ["neumann", "immaculata", "wilkes"],
  },
  wilkes: {
    name: "Wilkes University", shortName: "Wilkes", location: "Wilkes-Barre, PA",
    type: "Liberal Arts College", enrollment: "~2,400 undergrads",
    highlight: "Engineering, business, and health sciences with live catalog.",
    strengths: ["engineering", "business", "nursing", "computer science"],
    careerStrengths: ["engineering", "healthcare and nursing", "business"],
    signatureMajors: ["Engineering", "Business Administration", "Nursing", "Computer Science"],
    peerSlug: "neumann",
    relatedSlugs: ["neumann", "moravian", "misericordia"],
  },
  harding: {
    name: "Harding University", shortName: "Harding", location: "Searcy, AR",
    type: "Liberal Arts College", enrollment: "~4,300 undergrads",
    highlight: "Christian liberal arts with business, nursing, and education.",
    strengths: ["business", "nursing", "education", "pre-pharmacy"],
    careerStrengths: ["healthcare and nursing", "business", "education"],
    signatureMajors: ["Business Administration", "Nursing", "Education", "Psychology"],
    peerSlug: "johnbrown",
    relatedSlugs: ["johnbrown", "acu", "texaslutheran"],
  },
  acu: {
    name: "Abilene Christian University", shortName: "ACU", location: "Abilene, TX",
    type: "Liberal Arts College", enrollment: "~5,100 undergrads",
    highlight: "Christian university with engineering, nursing, and business programs.",
    strengths: ["engineering", "nursing", "business", "biblical studies"],
    careerStrengths: ["engineering and technology", "healthcare and nursing", "business"],
    signatureMajors: ["Engineering", "Nursing", "Business Administration", "Computer Science"],
    peerSlug: "johnbrown",
    relatedSlugs: ["johnbrown", "harding", "baylor"],
  },
  sfasu: {
    name: "Stephen F. Austin State University", shortName: "SFASU", location: "Nacogdoches, TX",
    type: "Public University", enrollment: "~10,500 undergrads",
    highlight: "Forestry, business, and health sciences at a regional Texas university.",
    strengths: ["forestry", "agriculture", "business", "health sciences"],
    careerStrengths: ["forestry and natural resources", "healthcare", "business"],
    signatureMajors: ["Forestry", "Business Administration", "Health Services", "Education"],
    peerSlug: "nwmissouri",
    relatedSlugs: ["nwmissouri", "midwesternstate"],
  },
  midwesternstate: {
    name: "Midwestern State University", shortName: "MSU Texas", location: "Wichita Falls, TX",
    type: "Public University", enrollment: "~5,800 undergrads",
    highlight: "Liberal arts and sciences with nursing and business programs.",
    strengths: ["nursing", "business", "education", "criminal justice"],
    careerStrengths: ["healthcare and nursing", "business", "education"],
    signatureMajors: ["Nursing", "Business Administration", "Education", "Criminal Justice"],
    peerSlug: "sfasu",
    relatedSlugs: ["sfasu", "nwmissouri"],
  },
  jarvis: {
    name: "Jarvis Christian University", shortName: "Jarvis", location: "Hawkins, TX",
    type: "Liberal Arts College", enrollment: "~700 undergrads",
    highlight: "HBCU in East Texas with business, education, and natural sciences.",
    strengths: ["business", "education", "natural sciences", "social sciences"],
    careerStrengths: ["business", "education and teaching", "healthcare"],
    signatureMajors: ["Business Administration", "Education", "Biology", "Social Sciences"],
    peerSlug: "fortvalleystate",
    relatedSlugs: ["fortvalleystate", "tougaloo", "elizabethcitystate"],
  },
  fortvalleystate: {
    name: "Fort Valley State University", shortName: "FVSU", location: "Fort Valley, GA",
    type: "Public University", enrollment: "~2,800 undergrads",
    highlight: "Georgia HBCU land-grant — agriculture, education, and STEM indexed.",
    strengths: ["agriculture", "education", "STEM", "business"],
    careerStrengths: ["agriculture and food science", "education", "engineering technology"],
    signatureMajors: ["Animal Science", "Computer Science", "Education", "Business Administration"],
    peerSlug: "jarvis",
    relatedSlugs: ["tougaloo", "ncat", "morehouse"],
  },
  ncat: {
    name: "North Carolina A&T State University", shortName: "NC A&T", location: "Greensboro, NC",
    type: "Research University", enrollment: "~14,000 undergrads",
    highlight: "Largest HBCU in the US — engineering, business, and agriculture indexed.",
    strengths: ["engineering", "agricultural sciences", "business management", "technology"],
    careerStrengths: ["engineering and aerospace", "agriculture and food science", "business"],
    signatureMajors: ["Electrical Engineering", "Computer Science", "Business Administration", "Agriculture"],
    peerSlug: "morehouse",
    relatedSlugs: ["morehouse", "morganstate", "winstonsalem"],
    freshmanNote: "NC A&T's engineering programs are the largest at any HBCU in the country — first-years enter major-specific cohorts with dedicated advising.",
  },
  winstonsalem: {
    name: "Winston-Salem State University", shortName: "WSSU", location: "Winston-Salem, NC",
    type: "Public University", enrollment: "~5,500 undergrads",
    highlight: "HBCU with nursing, business, and education programs indexed.",
    strengths: ["nursing", "business", "education", "health sciences"],
    careerStrengths: ["healthcare and nursing", "business", "education"],
    signatureMajors: ["Nursing", "Business Administration", "Health Sciences", "Education"],
    peerSlug: "ncat",
    relatedSlugs: ["ncat", "morganstate", "coppinstate"],
  },
  elizabethcitystate: {
    name: "Elizabeth City State University", shortName: "ECSU", location: "Elizabeth City, NC",
    type: "Public University", enrollment: "~1,500 undergrads",
    highlight: "HBCU in northeastern NC — aviation, education, and STEM programs.",
    strengths: ["aviation", "STEM", "education", "biology"],
    careerStrengths: ["aviation and aerospace", "education", "STEM fields"],
    signatureMajors: ["Aviation", "Computer Science", "Education", "Biology"],
    peerSlug: "winstonsalem",
    relatedSlugs: ["winstonsalem", "ncat", "jarvis"],
  },
  texaslutheran: {
    name: "Texas Lutheran University", shortName: "TLU", location: "Seguin, TX",
    type: "Liberal Arts College", enrollment: "~1,400 undergrads",
    highlight: "Lutheran liberal arts with business, education, and health sciences.",
    strengths: ["biology", "business", "education", "physics"],
    careerStrengths: ["healthcare and medicine", "business", "education"],
    signatureMajors: ["Biology", "Business Administration", "Education", "Physics"],
    peerSlug: "johnbrown",
    relatedSlugs: ["johnbrown", "acu", "harding"],
  },
};

export function getSchoolMeta(slug: string): SchoolMeta {
  return SCHOOLS[slug] ?? {
    name: slug.charAt(0).toUpperCase() + slug.slice(1),
    shortName: slug,
    location: "United States",
    type: "College or University",
    enrollment: "See school website",
    highlight: "Live course and faculty data indexed.",
  };
}

export const ALL_SLUGS = Object.keys(SCHOOLS);

export const SCHOOL_TYPE_ORDER = [
  "Research University",
  "Liberal Arts College",
  "Engineering College",
  "Public University",
  "Law School",
];
